site_name: PyDARN Documentation
repo_url: https://github.com/superdarn/pydarn
theme: readthedocs
markdown_extensions:
    - extra
    - admonition
    - toc

nav:
    - Home: index.md
    - About: about.md
    - Installation: user/install.md  
    - SuperDARN Data Access: user/superdarn_data.md 
    - Citing: user/citing.md
    - Tutorials:
        - Radar and Hardware Information: user/hardware.md 
        - Reading Files: user/io.md
        - Plotting:
            - Range-Time plots: user/range_time.md 
            - Time-Series plots: user/time_series.md 
            - Summary plots: user/summary.md
            - Power plots: user/power.md
            - ACF plots: user/acf.md
        - Logging: user/logging.md
        - Advanced Examples: user/examples.md
    - pyDARN Team:
        - Pull Requests:
            - Testing: dev/testing.md
            - Code Reviews: dev/code_review.md

